project:
  type: website
  resources: Assets
  output-dir: docs

website:
  title: "Jade Kay"
  navbar:
    background: "#0060A9"
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: Projects.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/jadekay/"
      - icon: github
        href: "https://github.com/jadekay03"
      - icon: file-pdf
        href: Assets/JadeKayResume2024.pdf

format:
  html:
    theme: spacelab
      # light: flatly
      # dark: darkly
        # - custom.scss
    css: styles.css
    toc: true


